# Pull official Python image
FROM python:3.12-slim

WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    curl \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements*.txt ./
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy app source
COPY . .

RUN curl -s -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x wait-for-it.sh

RUN chmod +x ./entrypoint.dev.sh

# Expose FastAPI port
EXPOSE 8000

# Entrypoint script will handle waiting + migration + app start
ENTRYPOINT ["./entrypoint.dev.sh"]
