# Pull official Python image
FROM python:3.12-slim

WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    curl \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements*.txt ./
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy app source
COPY . .

# Make the run_migrations.sh script executable and run it
RUN chmod +x run_migrations.sh && ./run_migrations.sh
    
# Make entrypoint script executable
RUN chmod +x ./entrypoint.dev.sh

# Expose FastAPI port
EXPOSE 8000

# Set default command
ENTRYPOINT ["./entrypoint.dev.sh"]

