# Pull official Python image
FROM python:3.12-slim

# Environment setup
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/usr/src/app \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /usr/src/app

# Install OS packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    curl \
    libzbar0 \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*



# Download wait-for-it.sh
RUN curl -sSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
    -o /usr/local/bin/wait-for-it.sh && chmod +x /usr/local/bin/wait-for-it.sh

# App user
RUN groupadd -r appgroup && useradd -r -g appgroup appuser

# Python dependencies
COPY requirements*.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy app source
COPY . .

RUN curl -s -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x wait-for-it.sh

RUN chmod +x ./entrypoint.dev.sh

# Expose FastAPI port
EXPOSE 8000

# Entrypoint script will handle waiting + migration + app start
ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]


