"""Migration message

Revision ID: 93c5ba2e877d
Revises: b3ef60c2900d
Create Date: 2025-06-29 04:47:25.323152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c5ba2e877d'
down_revision: Union[str, None] = 'b3ef60c2900d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'id',
               existing_type=sa.VARCHAR(length=27),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('addresses', 'user_id',
               existing_type=sa.VARCHAR(length=27),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=27),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=27),
               existing_nullable=False)
    op.alter_column('addresses', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=27),
               existing_nullable=False)
    op.alter_column('addresses', 'id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=27),
               existing_nullable=False)
    # ### end Alembic commands ###
